### ISSUE TITLE
Delete the bot

### ISSUE THREAD

**Issue by tnfAngel** [Discord-InterChat/discord-interchat.github.io#2]
I have run my own interchat bot (Called Chat Global), and the ratelimit is inevitable and will reach your nightmares, I spent many years developing the bot only to end badly, my bot reached 5k guilds and I had to delete it to end the suffering of the poor bot, when you sent a message, it doesn't matter how good a ratelimit manager you have, it will hit, or it will have hours of delay in propagating the message to all servers, just for a SINGLE message. It's not going to lead anywhere. 

If your bot has 5000 servers, and 100 messages are sent in a minute, 100x5000 = 500,000 requests per minute, when the discord limit is 10,000 per **10** minutes (1,000 per minute), the limit is ridiculous and will end very badly. 

I only say this to save you from my suffering when it happened to me, because it is unfeasible, but do what you want.

**Comment by LautyDev** [comment]
The gentleman above is absolutely right 🤓

**Comment by Soldier380** [comment]
The gentleman above is absolutely gay 🤓

**Comment by dev-737** [comment]
Hoping to find a breakthrough 🤞

**Comment by FrostSpikes** [comment]
we have some plans to help
